app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#app_book:
#    resource: |
#        alias: app.book
#        grid: app_book
#        redirect: update
#    type: sylius.resource
#    defaults: