sylius_grid:
    templates:
        action:
            show: "Grid/Action/show.html.twig"
            create: "Grid/Action/create.html.twig"
            update: "Grid/Action/update.html.twig"
            delete: "Grid/Action/delete.html.twig"
        filter:
            string: "Grid/Filter/string.html.twig"
            boolean: "Grid/Filter/boolean.html.twig"
    grids:
        app_book:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\Book

            fields:
                title:
                    type: string
                    label: Title
                author:
                    type: string
                    label: Author
                description:
                    type: string
                    label: description
            actions:
                main:
                    create:
                        type: update
                item:
                    update:
                        type: update
                    delete:
                        type: delete
            filters:
                title:
                    type: string
                author:
                    type: string



#sylius_grid:
#  grids:
#    app_book:
#      driver:
#        name: doctrine/orm
#        options:
#          class: AppBundle\Entity\Book
#      templates:
#        action:
#          show: "Grid/Action/show.html.twig"
#          create: "Grid/Action/create.html.twig"
#          update: "Grid/Action/update.html.twig"
#          delete: "Grid/Action/delete.html.twig"
#      fields:
#        title:
#          type: string
#          label: Title
#        author:
#          type: string
#          label: Author
#        description:
#          type: string
#          label: Description
#      actions:
#        main:
#          create:
#            type: create
#        item:
#          update:
#            type: update
#          delete:
#            type: delete