services:
    context.article:
        class: Behat\Context\Article\ArticleContext
        tags:
            - { name: fob.context_service }

    context.book:
        class: Behat\Context\Book\BookContext
        tags:
            - { name: fob.context_service }

    context.user:
        class: Behat\Context\User\UserContext
        tags:
            - { name: fob.context_service }